DOS-08032022/DOSUI/DOSUI/Models/DASSource.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DASReportRun.Models
{
    public class DASSource
    {
        public string Source_Office{get;set;}
        public string Source_Short{get;set;}
        public DateTime Source_Date{get;set;}
        public string Source_Transaction { get; set; }
        public string Source_Category { get; set; }
        public string Source_Ref { get; set; }
        public string Source_Address { get; set; }
        public double Source_Amount { get; set; }
        public string Source_Tenant { get; set; }
        public int Source_Claims { get; set; }
        public string Source_Period { get; set; }
        public int Source_Rent { get; set; }
        public int Source_RowID { get; set; }

  
       

    }
}

DOS-08032022/DOSUI/DOSUI/Controllers/DASSourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Excel = Microsoft.Office.Interop.Excel;
using DASReportRun.Models;
using System.Configuration;
using System.Data;
using System.Data.OleDb;

namespace DASReportRun.Controllers
{
    public class DASSourceController : Controller
    {
        // GET: DAS_Source_

        //public ActionResult Base()
        //{
        //    return View();
        //}

        [HttpPost]
        ////public ActionResult Import(HttpPostedFileBase excelFile)
        ////{
        ////    if (Session["model"] == null)
        ////    {
        ////        if (excelFile == null || excelFile.ContentLength == 0)
        ////        {
        ////            ViewBag.error = "Please select a excel file";
        ////            return View("Index");
        ////        }
        ////        else
        ////        {
        ////            if (excelFile.FileName.EndsWith("xls") || excelFile.FileName.EndsWith("xlsx"))
        ////            {

        ////                string filePath = string.Empty;

        ////                string path = Server.MapPath("~/Content/");

        ////                if (!Directory.Exists(path))

        ////                {

        ////                    Directory.CreateDirectory(path);

        ////                }

        ////                //get file path

        ////                filePath = path + Path.GetFileName(excelFile.FileName);

        ////                //get file extenstion

        ////                string extension = Path.GetExtension(excelFile.FileName);

        ////                //save file on "Uploads" folder of project

        ////                excelFile.SaveAs(filePath);



        ////                string conString = string.Empty;

        ////                //check file extension

        ////                switch (extension)

        ////                {

        ////                    case ".xls": //Excel 97-03.

        ////                       conString = ConfigurationManager.ConnectionStrings["Excel03ConString"].ConnectionString;
        ////                       // conString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + filePath + ";Extended Properties=\"Excel 8.0;HDR=Yes;IMEX=2\"";


        ////                        break;

        ////                    case ".xlsx": //Excel 07 and above.
        ////                        //conString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties=\"Excel 8.0;HDR=Yes\"";
        ////                        conString = ConfigurationManager.ConnectionStrings["Excel07ConString"].ConnectionString;

        ////                        break;

        ////                }



        ////                //create datatable object

        ////                DataTable dt = new DataTable();

        ////                conString = string.Format(conString, filePath);



        ////                //Use OldDb to read excel

        ////                using (OleDbConnection connExcel = new OleDbConnection(conString))

        ////                {

        ////                    using (OleDbCommand cmdExcel = new OleDbCommand())

        ////                    {

        ////                        using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())

        ////                        {

        ////                            cmdExcel.Connection = connExcel;



        ////                            //Get the name of First Sheet.

        ////                            connExcel.Open();

        ////                            DataTable dtExcelSchema;

        ////                            dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);

        ////                            string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();

        ////                            connExcel.Close();



        ////                            //Read Data from First Sheet.

        ////                            connExcel.Open();

        ////                            cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";

        ////                            odaExcel.SelectCommand = cmdExcel;

        ////                            odaExcel.Fill(dt);

        ////                            connExcel.Close();

        ////                        }

        ////                    }

        ////                }


        ////                List<DASSource> DASSourceList = new List<DASSource>();
        ////                for (int i = 2; i < dt.Rows.Count; i++)
        ////                {
        ////                    DASSource d = new DASSource();
        ////                    d.Source_Office = dt.Rows[i][0].ToString();
        ////                    d.Source_Short = dt.Rows[i][1].ToString();
        ////                    d.Source_Date = DateTime.Parse(dt.Rows[i][3].ToString());
        ////                    d.Source_Transaction = dt.Rows[i][4].ToString();
        ////                    d.Source_Category = dt.Rows[i][5].ToString();
        ////                    d.Source_Ref = dt.Rows[i][6].ToString();
        ////                    d.Source_Address = dt.Rows[i][7].ToString();
        ////                    d.Source_Amount = Convert.ToDouble(dt.Rows[i][8].ToString());
        ////                    d.Source_Tenant = dt.Rows[i][9].ToString();
        ////                    d.Source_Claims = Convert.ToInt32(dt.Rows[i][10].ToString());
        ////                    d.Source_Period = dt.Rows[i][11].ToString();
        ////                    d.Source_Rent = Convert.ToInt32(dt.Rows[i][12].ToString());

        ////                    d.Source_RowID = i - 1;
        ////                    DASSourceList.Add(d);
        ////                }
        ////                ViewBag.DASSourceList = DASSourceList;
        ////                Session["model"] = DASSourceList;
        ////                return View("Index", DASSourceList);
        ////                // return View("Success");
        ////                //return View(listsource);
        ////            }


        ////            else
        ////            {
        ////                ViewBag.error = "File Type is incorrect<br>";

        ////                return View("Index");
        ////            }

        ////        }
        ////    }
        ////    else
        ////    {
        ////        return View("Index", Session["model"]);
        ////    }
        ////}
        public ActionResult Import(HttpPostedFileBase excelFile)
        {
            if (Session["model"] == null)
            {
                if (excelFile == null || excelFile.ContentLength == 0)
                {
                    ViewBag.error = "Please select a excel file";
                    return View("Index");
                }
                else
                {
                    if (excelFile.FileName.EndsWith("xls") || excelFile.FileName.EndsWith("xlsx"))
                    {

                        string path1 = Server.MapPath("~/Content/");
                        string path = path1 + Path.GetFileName(excelFile.FileName);
                        //string path = excelFile.FileName;

                        if (System.IO.File.Exists(path))
                        {
                            System.IO.File.Delete(path);
                        }
                        
                        
                            excelFile.SaveAs(path);
                        
                        using (var stream = System.IO.File.Open(path, FileMode.Open, FileAccess.Write, FileShare.ReadWrite))
                        {
                            Excel.Application application = new Excel.Application();
                            Excel.Workbook workbook = application.Workbooks.Open(path);
                            Excel.Worksheet worksheet = workbook.ActiveSheet;
                            Excel.Range range = worksheet.UsedRange;
                            List<DASSource> DASSourceList = new List<DASSource>();
                            for (int row = 2; row < range.Rows.Count; row++)
                            {
                                DASSource d = new DASSource();
                                d.Source_Office = ((Excel.Range)range.Cells[row, 1]).Text;
                                d.Source_Short = ((Excel.Range)range.Cells[row, 2]).Text;
                                d.Source_Date = DateTime.Parse(((Excel.Range)range.Cells[row, 4]).Text);
                                d.Source_Transaction = ((Excel.Range)range.Cells[row, 5]).Text;
                                d.Source_Category = ((Excel.Range)range.Cells[row, 6]).Text;
                                d.Source_Ref = ((Excel.Range)range.Cells[row, 7]).Text;
                                d.Source_Address = ((Excel.Range)range.Cells[row, 8]).Text;
                                d.Source_Amount = Convert.ToDouble(((Excel.Range)range.Cells[row, 9]).Text);
                                d.Source_Tenant = ((Excel.Range)range.Cells[row, 10]).Text;
                                d.Source_Claims = Convert.ToInt32(((Excel.Range)range.Cells[row, 11]).Text);
                                d.Source_Period = ((Excel.Range)range.Cells[row, 12]).Text;
                                d.Source_Rent = Convert.ToInt32(((Excel.Range)range.Cells[row, 13]).Text);

                                d.Source_RowID = row - 1;
                                DASSourceList.Add(d);
                            }
                            ViewBag.DASSourceList = DASSourceList;
                            Session["model"] = DASSourceList;
                            return View("Index", DASSourceList);
                            // return View("Success");
                            //return View(listsource);
                        }
                    }

DOS-08032022/DOSUI/DOSUI/Views/DASSource/Index.cshtml
@model ICollection<DASReportRun.Models.DASSource>

@{
    // Layout = null;
    ViewBag.Title = "DAS Source";
}

<div style="width:100%;float:left;padding-bottom:50px;">

    <h4>DAS Source</h4>
    @using (Html.BeginForm("Import", "DASSource", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.Raw(ViewBag.error)
        <span>Excel File</span>
        <input type="file" name="excelfile" />
        <br />
        <input type="submit" value="Import" />

    }

    <a href="javascript://" id="btnAddNew">Add New </a>
    @{if (Model != null)
        {
            var grid = new WebGrid(Model, canPage: true,rowsPerPage: 10, selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContent"); grid.Pager(WebGridPagerModes.NextPrevious);
        <div id="gridContent" class="articleHeader article_lst">
            @grid.GetHtml(tableStyle: "webGrid",
    headerStyle: "",
    alternatingRowStyle: "alt",
    selectedRowStyle: "select",
    rowStyle:"border:1px",
        columns: grid.Columns(
        grid.Column("",
        style: "col1",
        format: @<text><div style="padding-left:20px;">
                    <button class="btn_grid edit-item display-mode" id="@item.Source_RowID">Edit</button>
                    <button class="btn_grid  display-mode delete-item" id="@item.Source_RowID">Delete</button>
                    <button class="btn_grid save-item edit-mode" style="display:none" id="@item.Source_RowID">Save</button>
                    <button class="btn_grid cancel-item edit-mode" style="display:none" id="@item.Source_RowID">Cancel</button>
                    @*<button class="btn_grid save-item edit-mode" id="@item.Source_RowID">Save</button>
                <button class="btn_grid cancel-item edit-mode" id="@item.Source_RowID">Cancel</button>*@
                </div>
        </text>),
grid.Column("Source_RowID","ROW ID"),
grid.Column("Office",
style: "col2",
format:@<text>
            <span id="Source_Office" class="display-mode">@item.Source_Office</span>
            @Html.TextBox("Source_Office-Edit", (string)item.Source_Office, new { @class = "edit-mode" })
        </text>),
grid.Column("Short",
style: "col3",
format:@<text>
                <span id="Source_Short" class="display-mode">@item.Source_Short</span>
                @Html.TextBox("Source_Short-Edit", (string)item.Source_Short, new { @class = "edit-mode" })
        </text>),

grid.Column("Date", format:@<text>
                @{ if (item.Source_Date != null)
                             { <span id="Source_Date" class="display-mode">@item.Source_Date.ToShortDateString()</span>}}
                <input id="Source_Date-Edit" type="date" class="edit-mode datepicker" />
        </text>),
grid.Column("Transaction",
style: "col4", format:@<text>
                <span id="Source_Transaction" class="display-mode">@item.Source_Transaction</span>
                @Html.TextBox("Source_Transaction-Edit", (string)item.Source_Transaction, new { @class = "edit-mode" })
        </text>),
grid.Column("Category",
style: "col5", format:@<text>
                <span id="Source_Category" class="display-mode">@item.Source_Category</span>
                @Html.TextBox("Source_Category-Edit", (string)item.Source_Category, new { @class = "edit-mode" })
        </text>),
grid.Column("Ref",
style: "col6", format:@<text>
                <span id="Source_Ref" class="display-mode">@item.Source_Ref</span>
                @Html.TextBox("Source_Ref-Edit", (string)item.Source_Ref, new { @class = "edit-mode" })
        </text>),
grid.Column("Address",
style: "col7", format:@<text>
                <span id="Source_Address" class="display-mode">@item.Source_Address</span>
                @Html.TextBox("Source_Address-Edit", (string)item.Source_Address, new { @class = "edit-mode" })
        </text>),
grid.Column("Amount",
style: "col8", format:@<text>
                <span id="Source_Amount" class="display-mode">@item.Source_Amount</span>
                @Html.TextBox("Source_Amount-Edit", (double)item.Source_Amount, new { @class = "edit-mode" })
        </text>),

grid.Column("Tenant",
style: "col4", format:@<text>
                <span id="Source_Tenant" class="display-mode">@item.Source_Tenant</span>
                @Html.TextBox("Source_Tenant-Edit", (string)item.Source_Tenant, new { @class = "edit-mode" })
        </text>),
grid.Column("Claims",
style: "col4", format:@<text>
                <span id="Source_Claims" class="display-mode">@item.Source_Claims</span>
                @Html.TextBox("Source_Claims-Edit", (int)item.Source_Claims, new { @class = "edit-mode" })
        </text>),
grid.Column("Period",
style: "col4", format:@<text>
                <span id="Source_Period" class="display-mode">@item.Source_Period</span>
                @Html.TextBox("Source_Period-Edit", (string)item.Source_Period, new { @class = "edit-mode" })
        </text>),
grid.Column("Rent",
style: "col4", format:@<text>
                <span id="Source_Rent" class="display-mode">@item.Source_Rent</span>
                @Html.TextBox("Source_Rent-Edit", (int)item.Source_Rent, new { @class = "edit-mode" })
        </text>)

))
        </div>


}

}
    </div>
<script type="text/javascript"> 
    $(document).ready(function () {
        $('.webGrid').find('tr td input').hide();
        //initialize();
        //function initialize() {
        //$(".datepicker").datepicker({ format: 'dd/mm/yyyy', autoclose: true, todayBtn: 'linked' });
        //   $(".datepicker").datepicker("update", new Date());
        //$("#datepicker").datepicker({ format: 'dd/mm/yyyy', autoclose: true, todayBtn: 'linked' });
        //   $("#datepicker").datepicker("update", new Date());
        $('#btnAddNew').click(function () {
            if ($('.add-item').length == 0) {

                var newRow = $("<tr>");
                newRow.append("<td style='padding-left:20px'><button class='btn_grid add-item edit-mode' Source_RowID='0'>Add </button>&nbsp;<button class='btn_grid remove-item edit-mode' Source_RowID='0'>Cancel</button></td>");
                newRow.append("<td>&nbsp;</td>");
                newRow.append("<td><input type='text' id='Source_Office-Add'/></td>");
                newRow.append("<td><input type='text' id='Source_Short-Add'/></td>");
                newRow.append("<td><input  id='Source_Date-Add' class='datepicker' value='EnterDate'/></td>");
                newRow.append("<td><input type='text' id='Source_Transaction-Add'/></td>");

                $('#gridContent tbody:last').append(newRow);
                //$(".datepicker").datepicker({ format: 'dd/mm/yyyy', autoclose: true, todayBtn: 'linked' })
                //$(".datepicker").datepicker("update", new Date());
            }

            $('.add-item').on('click', function () {
                var tr = $(this).parents('tr:first');
                var Source_RowID = $(this).prop('Source_RowID');
                var Source_Office = tr.find('#Source_Office-Add').val();
                var Source_Short = tr.find('#Source_Short-Add').val();
                var Source_Date = tr.find('#Source_Date-Add').val();
                var Source_Discription = tr.find('#Source_Discription-Add').val();
                var Source_Category = tr.find('#Source_Category-Add').val();
                var Source_Ref = tr.find('#Source_Ref-Add').val();
                var Source_Address = tr.find('#Source_Address-Add').val();
                var Source_Amount = tr.find('#Source_Amount-Add').val();
                var Source_Tenant = tr.find('#Source_Tenant-Add').val();
                var Source_Claims = tr.find('#Source_Claims-Add').val();
                var Source_Period = tr.find('#Source_Period-Add').val();
                var Source_Rent = tr.find('#Source_Rent-Add').val();

                $.post(
                    '/DASSource/SaveSource/',
                    {
                        Source_RowID: Source_RowID, Source_Office: Source_Office, Source_Short: Source_Short, Source_Date: Source_Date, Source_Discription: Source_Discription,Source_Category: Source_Category, Source_Ref: Source_Ref, Source_Address: Source_Address, Source_Amount: Source_Amount, Source_Tenant: Source_Tenant, Source_Claims: Source_Claims, Source_Period: Source_Period, Source_Rent: Source_Rent },
                    function (item) {
                        tr.find('#Source_Office').text(item.Source_Office);
                        tr.find('#Source_Short').text(item.Source_Short);
                        tr.find('#Source_Date').text(item.Source_Date);
                        tr.find('#Source_Discription').text(item.Source_Discription);
                        tr.find('#Source_Category').text(item.Source_Category);
                        tr.find('#Source_Ref').text(item.Source_Ref);
                        tr.find('#Source_Address').text(item.Source_Address);
                        tr.find('#Source_Amount').text(item.Source_Amount);
                        tr.find('#Source_Tenant').text(item.Source_Tenant);
                        tr.find('#Source_Claims').text(item.Source_Claims);
                        tr.find('#Source_Period').text(item.Source_Period);
                        tr.find('#Source_Rent').text(item.Source_Rent);

                    }, "json");
                tr.remove();
            });

        });

        //$('.edit-mode').hide()

        $('.edit-item').on('click', function () {
            $('.edit-mode').hide();
            $('.delete-mode').hide();
            $('.display-mode').show();
            var tr = $(this).parents('tr:first');
            tr.find('.edit-mode,.display-mode').toggle();
        });


        $('.cancel-item').on('click', function () {
            var tr = $(this).parents('tr:first');
            tr.find('.display-mode,.edit-mode').toggle();

        });

        $('.delete-item').on('click', function () {
            if (confirm("Are you sure to delete this Entry?")) {
                var tr = $(this).parents('tr:first');
                var Source_RowID = $(this).prop('Source_RowID');
                $.post(
                    '/DASSource/DeleteSource/',
                    { Source_RowID: Source_RowID },
                    function (item) {

                        tr.remove();
                    }, "json");
            }
        });


        $('.save-item').on('click', function () {
            var tr = $(this).parents('tr:first');
            var Source_RowID = $(this).prop('Source_RowID');
            var Source_Office = tr.find('#Source_Office-Edit').val();
            var Source_Short = tr.find('#Source_Short-Edit').val();
            var Source_Date = tr.find('#Source_Date-Edit').val();
            var Source_Discription = tr.find('#Source_Discription-Edit').val();
            var Source_Category = tr.find('#Source_Category-Edit').val();
            var Source_Ref = tr.find('#Source_Ref-Edit').val();
            var Source_Address = tr.find('#Source_Address-Edit').val();
            var Source_Amount = tr.find('#Source_Amount-Edit').val();
            var Source_Tenant = tr.find('#Source_Tenant-Edit').val();
            var Source_Claims = tr.find('#Source_Claims-Edit').val();
            var Source_Period = tr.find('#Source_Period-Edit').val();
            var Source_Rent = tr.find('#Source_Rent-Edit').val();
            $.post(
                '/DASSource/SaveSource/',
                { Source_RowID: Source_RowID, Source_Office: Source_Office, Source_Short: Source_Short, Source_Date: Source_Date, Source_Discription: Source_Discription, Source_Category: Source_Category, Source_Ref: Source_Ref, Source_Address: Source_Address, Source_Amount: Source_Amount, Source_Tenant: Source_Tenant, Source_Claims: Source_Claims, Source_Period: Source_Period, Source_Rent: Source_Rent },
                function (item) {
                    tr.find('#Source_Office').text(item.Source_Office);
                    tr.find('#Source_Short').text(item.Source_Short);
                    tr.find('#Source_Date').text(item.Source_Date);
                    tr.find('#Source_Discription').text(item.Source_Discription);
                    tr.find('#Source_Category').text(item.Source_Category);
                    tr.find('#Source_Ref').text(item.Source_Ref);
                    tr.find('#Source_Address').text(item.Source_Address);
                    tr.find('#Source_Amount').text(item.Source_Amount);
                    tr.find('#Source_Tenant').text(item.Source_Tenant);
                    tr.find('#Source_Claims').text(item.Source_Claims);
                    tr.find('#Source_Period').text(item.Source_Period);
                    tr.find('#Source_Rent').text(item.Source_Rent);

                }, "json");
            tr.find('.edit-mode,.display-mode').toggle();
            window.location.href("/DASSource/Index/");
        });
    }
    );
    
           
</script>

DOS-08032022/DOSUI/DOSUI/Views/DASSource/Success.cshtml
@model DASReportRun.Models.DASSource
<style>
 .table {
     border-collapse:collapse!important;
 }
    .table-bordered th,
    .table-bordered td {
        border: 1px solid black !important;
        
        
    }
</style>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Success</title>
</head>
<body>
  
    <div> 
        <div>
            Office:<input type="text" id="txtOffie" />   @*@Html.TextBoxFor(x => x.Office, new {@class="form-control"})*@
        </div>
      <table class="table table-bordered" style="width:100%">

            <tr style="width:100%">
                <th>Office</th>
                <th>short</th>
                <th>Date</th>
                <th>Transaction</th>

            </tr>
            <tbody>
                @foreach (var d in ViewBag.ListSource)
                {
                    <tr>
                        <td>
                            @d.Office
                        </td>
                        <td>@d.Short</td>
                        <td>@d.Date</td>
                        <td>@d.Transaction</td>
                    </tr>
                }
            </tbody>
        </table>
        
    </div>
</body>
</html>